Improve tests and extend TableIOPlugin
scijava/scijava-plugins-io-table pull request #6
Opened 2020-05-10 21:41 UTC by frauzufall

I'm working on a bunch of issues / enhancements discussed [here](https://github.com/scijava/scijava-plugins-io-table/issues/5). The code depends on [this scijava-table branch](https://github.com/scijava/scijava-table/tree/tableioservice-options).

Changes:
- read and write row and column headers by default
- `DefaultTableIOPlugin` extends `TableIOPlugin`
- removed the plugin parameters, making use of `TableIOOptions` instead
- guess column types based on first data row

2020-07-06 18:59 UTC, imagejan commented on src/test/java/org/scijava/table/DefaultTableIOPluginTest.java
> -			setValues(tableIO, new String[] { "readRowHeaders" }, new Object[] {
The private method `setValues()` can now be removed, as it is never used.

2020-07-20 19:38 UTC, imagejan requested changes
Thanks @frauzufall, I think this PR is almost good to be merged. There are just a few minor changes I'd like to see:

* [x] remove commented code (`DISCUSS`)
* [x] remove `setValues` in `DefaultTableIOPluginTest` (line 314-327)

We can also improve test coverage by adding:

* tests opening files with varying row length (throwing `IOException` -- or maybe ignoring it as an option?)
* test `guessParser` for `Integer`, `Long` and `Float` in addition to `Double`
* test `save(Table, String)` signature
* test a few more invalid/error cases

But I guess these things can wait for a later pull request.

2020-07-20 19:38 UTC, imagejan commented on pom.xml
> +			<version>1.0.0</version>
We should make this a version property, i.e.:
```suggestion
			<version>${scijava-optional.version}</version>
```

2020-07-20 19:38 UTC, imagejan commented on src/main/java/org/scijava/table/DefaultTableIOPlugin.java
> +//						.getRowHeader(row) != null));
I agree we should aim for predictable and deterministic behavior. Guessing whether to write row and/or column headers should be opt-in (if at all).

2020-07-25 12:12 UTC, frauzufall commented
Thanks for the comments @imagejan! 

About testing `guessParser` for `Long` and `Float`: I'm not sure how to do this and I'm also not sure if the `guessParser` method works as expected there. 

This test fails, because the String can and therefore will be interpreted as Integer:
```
assertEquals(3L, DefaultTableIOPlugin.guessParser("3L").apply("3L"));
```
Using a number too big for an Integer should work, I thought, but this also fails and I don't understand why:
```
assertEquals(36564573745634564L, DefaultTableIOPlugin.guessParser("36564573745634564L").apply("36564573745634564L"));
```
Here is the result:
```
java.lang.AssertionError: 
Expected :36564573745634564
Actual   :36564573745634564L
```

Similar problem with Float. Maybe I'm missing something very basic about how numbers are represented.

2020-07-25 12:54 UTC, imagejan commented
@frauzufall wrote:
> `assertEquals(36564573745634564L, DefaultTableIOPlugin.guessParser("36564573745634564L").apply("36564573745634564L"));`

`36564573745634564L` will be interpreted as a `String` because of the trailing `L`, no?

I added a slightly modified line:

https://github.com/scijava/scijava-plugins-io-table/blob/922e92590ddd7294e11578250d8c5481f20109a9/src/test/java/org/scijava/table/DefaultTableIOPluginTest.java#L258

... and it passes.

---

However, we now still have dead code with the `Float.valueOf`, as this one will never be reached because any decimal number can be interpreted by `Double.valueOf` here:

https://github.com/scijava/scijava-plugins-io-table/blob/922e92590ddd7294e11578250d8c5481f20109a9/src/main/java/org/scijava/table/DefaultTableIOPlugin.java#L255-L262

2020-08-03 09:12 UTC, frauzufall commented
@imagejan Thanks! I removed the dead code. It will just always use double when guessing, that's fine, right? I'm sure the guessing can be further improved, but we probably need to release a new version of this repo too before uploading the most recent version of `scijava-table` to Fiji..

2020-08-03 09:18 UTC, merged